"2019-08-24 12:01:43,617 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:01:43,617 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:01:44,117 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:01:44,117 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:05,604 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:05,604 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:05,607 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:05,608 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:26,441 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:26,442 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:27,039 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:27,039 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:47,543 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:47,544 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:47,589 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:47,589 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:58,119 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:58,119 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:58,120 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:02:58,120 - data_overview.py[line:90] - WARNING: destroy Dtable error,:'NoneType' object has no attribute 'destroy', but this can be ignored sometimes"
"2019-08-24 12:09:37,345 - data_overview.py[line:90] - WARNING: destroy Dtable error,:/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/08e29ce0-c668-11e9-9e8a-0242ac110002/0: No such file or directory, but this can be ignored sometimes"
"2019-08-24 12:13:06,971 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: '/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/851d2578-c668-11e9-9e8a-0242ac110002', but this can be ignored sometimes"
"2019-08-24 12:17:34,382 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: '/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/2470baea-c669-11e9-9e8a-0242ac110002', but this can be ignored sometimes"
"2019-08-24 12:18:06,229 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: 'lock.mdb', but this can be ignored sometimes"
"2019-08-24 12:20:38,593 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: '/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/9236b994-c669-11e9-9e8a-0242ac110002', but this can be ignored sometimes"
"2019-08-24 12:21:19,894 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: '/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/aba70208-c669-11e9-9e8a-0242ac110002', but this can be ignored sometimes"
"2019-08-24 12:21:41,068 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: '/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/b7c3677a-c669-11e9-9e8a-0242ac110002', but this can be ignored sometimes"
"2019-08-24 12:21:51,218 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: '/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/be3ca99a-c669-11e9-9e8a-0242ac110002', but this can be ignored sometimes"
"2019-08-24 12:25:37,078 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: 'data.mdb', but this can be ignored sometimes"
"2019-08-24 12:28:44,013 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: '/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/b3e71998-c66a-11e9-9e8a-0242ac110002', but this can be ignored sometimes"
"2019-08-24 12:32:03,695 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 2] No such file or directory: '/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/2afb8ff0-c66b-11e9-9e8a-0242ac110002', but this can be ignored sometimes"
"2019-08-24 12:36:32,073 - data_overview.py[line:90] - WARNING: destroy Dtable error,:[Errno 39] Directory not empty: '/fate/data/IN_MEMORY/hetero_network_embedding_example_standalone_20190824115846/cb7dcd76-c66b-11e9-9e8a-0242ac110002', but this can be ignored sometimes"
